@startuml

title US018

/'
As Product Owner, I want the system to have a type of sensor that gives the
current value/position in a scale (%).
'/

interface Sensor {
    + getId() : int
    + generateId(int) : int
    + getType() : SensorType
    + getValue() : Value
}

class SensorOfScalePercentage {
    - id : int
    + SensorOfScalePercentage()
    + getId() : int
    + generateId(int) : int
    + getType() : SensorType
    + getValue() : Value
}

interface Value {
    + valueToString() : String
}

class ScalePercentageValue {
    - percentageValue : double
    + ScalePercentageValue(double)
    + valueToString() : String
}

enum SensorType {
    - sensorType : String
    - measureUnit : String
    + SensorType(...)
    + getSensorType() : String
}

Sensor <|.. SensorOfScalePercentage : " implements       "
Value <|.. ScalePercentageValue : " implements"
SensorOfScalePercentage "1  " *-- "1    " ScalePercentageValue :  "  has"
SensorOfScalePercentage "1  " o-- "1  " SensorType :  "  has"

@enduml