@startuml

title CLASS DIAGRAM (G6))

package "House Ag."{
class House {
  + House (...)
  + getLocation() : Location
  + defineLocation(...) : boolean
}

class Location {
  + Location(...)
  + getAddress() : String
  + getGPSLocation() : GPS
}

class Address{
 - street: Street
 - zipCode:ZipCode
 - city: City
 - number: Number
 + Address(...)
 + getStreet(): Street
 + getZipCode(): ZipCode
 + getCity(): City
 + getNumber(): Number
}

class GPS{
    - latitude: Latitude
    - longitude: Longitude
    + GPS(...)
    + getLatitude(): Latitude
    + getLongitude(): Longitude
  }
  }


class HouseName{
- houseName: String
+ HouseName(...)
+ getHouseName(): String
}




package "Room Ag."{
class Room {
  + Room(...)
  + getName() : RoomName
  + getFloor() : Floor
  + getDimensions() : Dimensions
}

class Dimensions {
  - width : Width
  - length : Length
  - height : Height
  + Dimensions(...)
  + getWidth() : Width
  + getLength() : Length
  + getHeight() : Height
}

class Floor{
 - floor: int
 + Floor(...)
 + getFloor(): int
}

}

class RoomName{
- roomName: String
+ RoomName(...)
+ getRoomName(): String
}

package "Device Ag."{
class Device {
  + Device(...)
  + getName() : DeviceName
  + getRoomName() : RoomName
  + getType() : DeviceType
  + deactivate() : Status
}


class DeviceType{
- type: String
+ DeviceType(...)
+ getType(): String
    }

class Status{
- active: boolean
+ Status(...)
+ isActive(): boolean
}
}
class DeviceName{
- deviceName: String
+ DeviceName(...)
+ getDeviceName(): String
    }

package "Sensor Ag."{

interface Sensor {
  + getType() : SensorType
  + getValue() : Value
  + getDeviceName() : DeviceName
  + getId() : SensorId
}

enum SensorType{
+ getSensorType(): String
}

interface Value{
  + valueToString() : String
}

class SensorId{
- id: int
+ SensorId(...)
+ getId(): int}


}
}

package "Actuator Ag."{
interface Actuator{
    +getType(): ActuatorType
    +operate(): void
    +getId():int
    +generateId(): ActuatorId
}
enum ActuatorType{
}

class ActuatorId{
- id: int
+ ActuatorId(...)
+ getId(): int
}

}

package "Utils"{
class IdGenerator{
- static sensorId:int
- static actuatorId:int
+ static generateSensorId:int
+ static generateActuatorId:int
+ static resetSensorId: void
+ static resetActuatorId: void
}


class Catalogue {
  - actuatorClassList : List<String>
  - sensorClassList : List<String>
  +Catalogue(...)
  + getSensorsCatalogue() : List<String>
  + getActuatorsCatalogue() : List<String>
}

}





House "1" *-- "1" Location : contains
House "1" *-- "1" HouseName : contains
Location "1" *-- "1" Address : contains
Location "1" *-- "1" GPS : contains

Room "1" *-- "1" RoomName : contains
Room "1" --> "1" HouseName : knows
Room "1" *-- "1" Floor : contains
Room "1" *-- "1" Dimensions : contains

Device "1" *-- "1" DeviceName : contains
Device "1" --> "1" RoomName : knows
Device "1" *-- "1" DeviceType : contains
Device "1" *-- "1" Status : contains

Sensor "1" *-- "1" SensorType : has
Sensor "1" *-- "1" Value : contains
Sensor "1" --> "1" DeviceName : knows
Sensor "1" *-- "1" SensorId : contains

Actuator "1" *-- "1" ActuatorType : has
Actuator "1" *-- "1" ActuatorId : contains
Actuator "1" --> "1" DeviceName : knows



@enduml