@startuml

class House {
    - rooms : List<Room>
    + getRoomList() : List<Room>
    + getRoomByName(...) : Room
}

class Room {
    - name : String
    - floor : int
    - deviceFactory : DeviceFactory
    - devices : List<Device>
    + getName() : String
    + getFloor() : int
    + getDimensions() : Dimensions
    + addNewDevice() : Device
    - validDeviceName() : boolean
}

class Dimensions{
    - width : double
    - length : double
    - height : double

    + getWidth() : double
    + getLength() : double
    + getHeight() : double
}

class Device{
    + name : String
    + type : String

    + Device(...)
}

class DeviceDTO {
    - name : String
    - type : String
    - roomName : String
    + DeviceDTO(...)
    + getName() : String
    + getType() : String
    + getRoomName() : String
}

class AddDeviceToRoomController {
    - house : House
    - deviceMapper : DeviceMapper
    - getRoomListController : GetRoomListController
    + AddDeviceToRoomController(...)
    + getRooms() : List<RoomDTO>
    + addDeviceToRoom(...) : DeviceDTO
}

class GetRoomListController {
    - house : House
    - roomMapper : RoomMapper
    + GetRoomListController(...)
    + getRoomList() : List<RoomDTO>
}

class DeviceMapper {
    + deviceToDTO(...) : DeviceDTO
}

class RoomMapper {
    + RoomMapper()
    + getRooms(...) : List<RoomDTO>
    - roomToDTO(...) : RoomDTO
}

class RoomDTO {
    - name : String
    - floor : int
    - width : double
    - length : double
    - height : double
    + RoomDTO(...)
    + getName() : String
    + getFloor() : int
    + getWidth() : double
    + getLength() : double
    + getHeight() : double
}

AddDeviceToRoomController "1" ..> "1" House : uses
GetRoomListController "1" ..> "1" House : uses
House "1" *-- "*" Room : contains
AddDeviceToRoomController "1" ..> "1" DeviceMapper : uses
DeviceMapper "1" ..> "*" DeviceDTO : creates
Room "1" *-- "*" Device : contains
AddDeviceToRoomController "1" ..> "1" GetRoomListController : uses
AddDeviceToRoomController "1" ..> "1" DeviceDTO : uses
GetRoomListController "1" ..> "1" RoomMapper : uses
RoomMapper "1" ..> "*" RoomDTO : creates
Room "1" *-- "1" Dimensions : has

@enduml