@startuml

interface Sensor {

  + getType() : String
  + getName() : String
  + getValue() : double
}

class SensorOfHumidity {
  - name : String
  - type : String
  - value : double

  + SensorOfHumidity(...)
  + getName() : String
  + getType() : String
  + getValue() : double
}

class HumidityValue {
  - humidityValue: int

  + HumidityValue()
  + getHumidityValue() : int
  + toValue() : String
}

interface Value {
  + toValue() : String
}

SensorOfHumidity "*" ..|> "1" Sensor : implements
SensorOfHumidity "1" *-- "1" HumidityValue : has

HumidityValue "*" ..|> "1" Value : implements

@enduml