@startuml
'https://plantuml.com/sequence-diagram

title US012

autonumber

/'
As a Power User [or Administrator], I want to add an actuator to an existing
device in a room. The actuator must be of a model of an existing type of actuator.
'/

participant "addActuatorToDeviceController:AddActuatorToDeviceController" as C12
participant "getRoomList:GetRoomListController" as C
participant "getDeviceList:GetDeviceListController" as D
participant "house:House" as H
participant "catalogue:Catalogue" as CAT
participant "room:Room" as R
participant "device:Device" as D1
participant "actuatorFactory:ActuatorFactory" as F
participant "actuator:Actuator" as A1
participant "actuatorMapper:ActuatorMapper" as AM
participant "actuatorDTO:ActuatorDTO" as ADT

[o->C12 : getRooms()
activate C12
C12->C : getRooms()
activate C
ref over C : (UserStory3.puml for more details)
C12<--C : roomsDTO
deactivate C
[o<--C12 : roomsDTO
deactivate C12

[o->C12 : getDevices(roomDTO)
activate C12
C12->D : getDevicesInRoom(roomName)
activate D
ref over D : (UserStory6.puml for more details)
C12<--D : devicesDTO
deactivate D
[o<--C12 : devicesDTO
deactivate C12

[o->C12: getActuatorModels()
activate C12
C12->CAT : getActuatorsCatalogue()
activate CAT
CAT-->C12 : actuatorModels
deactivate CAT
[o<--C12 : actuatorModels
deactivate C12

[o->C12: addActuatorToDevice(deviceDTO, actuatorModel)
activate C12
C12->H : getRoomByName(roomName)
activate H
H-->C12 : room
deactivate H

C12->R : getDeviceByName(deviceName)
activate R
R-->C12 : device
deactivate R

C12->D1 : addActuator(actuatorModel)
activate D1
D1-> F : createActuator(actuatorClassName)
activate F
F -> A1 ** : <create> (actuatorClassName)
F --> D1 : actuator
deactivate F
D1 -> D1 : actuators.add(actuator)
D1 --> C12 : actuator
deactivate D1
C12 -> AM : actuatorToDTO(actuator)
activate AM
AM -> ADT** : <create> (id, actuatorType)
AM --> C12 : actuatorDTO
deactivate AM
[o<--C12 : actuatorDTO
deactivate C12

@enduml