@startuml

autonumber

title US001

/'
As an Administrator, I want to configure the location of the house.
'/

participant "locationController:DefineHouseLocationController" as LC
participant "house:House" as H
participant "locationFactory:LocationFactoryImp" as LF
participant "location:Location" as L
participant "gpsFactory:GPSFactoryImp" as GF
participant "gps:GPS" as G
participant "locationMapper:LocationMapper" as LM
participant "locationDTO:LocationDTO" as LDT


[o-> LC : defineHouseLocation(LocationDTO)
activate LC
LC -> H : defineLocation(address, zipCode, latitude, longitude)
activate H
H -> LF: createLocation(address, zipCode, latitude, longitude)
activate LF
LF --> L** : <create> (address, zipCode, latitude, longitude)
activate L
L -> GF : createGPS(latitude, longitude)
activate GF
GF -->G** : <create> (latitude, longitude)
GF -->L : gps
deactivate GF
L -->LF : location
deactivate L
LF --> H : location
deactivate LF
H --> LC : location
deactivate H

LC -> LM : locationToDTO(location)
activate LM
LM -->LDT** : <create> (address, zipCode, latitude, longitude)
LM -->LC : locationDTO
deactivate LM
[o<--LC : locationDTO
deactivate LC

@enduml