@startuml

class House {

  + getRoomByName(...) : Room
  + getRoomList() : List<Room>
}

class Room {
  - name : String
  
  + Room(...)
  + getName() : String
  + getDeviceList() : List<Device>
  + getDeviceByName() : Device
}

class Device {
  - name : String
  - active : boolean
  
  + Device(...)
  + getName() : String
  + deactivate() : boolean
}

class DeviceDTO { 
  - name : String
  - location : String
  
  + DeviceDTO(...)
  + getName() : String
  + getLocation() : String
}

class RoomDTO {
    - name : String
  
    + RoomDTO(...)
    + getName() : String
}

class DeactivateDeviceController {
    - house : House

    + DeactivateDeviceController(...)
    + getRoomList() : List<RoomDTO>
    + getDeviceList(...) : List<DeviceDTO>
    + deactivateDevice(...) : boolean
}

class GetRoomListController {
    - house : House

    + GetRoomListController()
    + getRoomList() : List<RoomDTO>
}

class GetDeviceListController {
    - house : House

    + GetDeviceListController()
    + getDeviceList(...) : List<DeviceDTO>
}

class MapperToRoomDTO {

    + MapperToRoomDTO()
    + getRoomList(...) : List<RoomDTO>
    - toRoomDTO(...) : RoomDTO
}

class MapperToDeviceDTO {

  + MapperToDeviceDTO()
  + getDeviceList(...) : List<DeviceDTO>
  - toDeviceDTO(...) : DeviceDTO
}

DeactivateDeviceController "1" .> "1" GetRoomListController : uses
GetRoomListController "1" --> "1" MapperToRoomDTO : creates
MapperToRoomDTO "1" --> "List<RoomDTO>" RoomDTO : creates
GetRoomListController "1" .> "1" House : uses

DeactivateDeviceController "1".> "1" House : uses
House "1" --> "List<Room>" Room : contains
Room "1" --> "List<Device>" Device : contains

DeactivateDeviceController "1" -.> "1" GetDeviceListController : uses
GetDeviceListController "1" --> "1" MapperToDeviceDTO : creates
MapperToDeviceDTO "1" --> "List<DeviceDTO>" DeviceDTO : creates
GetDeviceListController "1" .> "1" House : uses

@enduml