@startuml


autonumber

participant "addRoomController:AddRoomController" as ARC
participant "house:House" as H
participant "roomFactory:RoomFactory" as RF
participant "room:Room" as R
participant "mapperRoomDTO" as M
participant "roomDTO:RoomDTO" as DTO

[o-> ARC: addNewRoomToHouse(roomDTO)
ARC -> H: addNewRoomToHouse(roomName, floor, width, length, height)
H -> RF: createRoom(roomName, floor, width, length, height)
RF --> R**: <creates>(roomName, floor, width, length, height)
H <-- RF: room


H --> ARC: room
ARC -> M: mapperToRoomDTO(room)
M --> DTO**: <creates>(room)
M --> ARC: : roomDTO
[o<--ARC: roomDTO




@enduml