@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant "_getRoomList:GetRoomListController" as C
participant "_getDeviceList:GetDeviceListFromSpecificRoomController" as D
participant "_getSensorTypeList:GetSensorTypesController" as S
participant "_addSensorToSpecificDeviceController:AddSensorToSpecificDeviceController" as C7
participant "_house:House" as H
participant "_catalogue:Catalogue" as CAT
participant "_mapperSensorTypeListDTO:MapperSensorTypeListDTO" as M
participant "_listSensorTypesDTO:List<SensorTypeDTO>" as L
participant "_room:Room" as R
participant "_device:Device" as D1
participant "_sensorList:List<Sensor>" as SL
participant "_sensorFactory:SensorFactory" as F
participant "_sensor:Sensor" as S1
participant "_mapperSensorToSensorDTO:MapperSensorToSensorDTO" as M1
participant "_sensorDTO:SensorDTO" as S2

[o->C : getRoomList()
activate C
ref over C,D : (UseCase06.puml for more details)
[o<--C : _deviceListDTO
deactivate C
[o->S: getSensorTypes()
activate S
S->H : getCatalog()
activate H
H-->S : _catalogue
deactivate H
S->CAT : getSensorTypes()
activate CAT
CAT-->S : _sensorTypes
deactivate CAT
activate M
S->M : mapSensorTypesDTO(_sensorTypes)
M-->L** : create(_sensorTypes)

M-->S: _sensorTypesDTO
deactivate M
[o<--S : _sensorTypesDTO
deactivate S

[o->C7: addSensorToDevice(DeviceDTO _deviceDTO, SensorDTO _sensorDTO)
activate C7
C7->H: getRoomByName(String _roomName)
activate H
H-->C7: _room
deactivate H
C7->R: getDeviceByName(String _deviceName)
activate R
R-->C7: _device
deactivate R
C7->D1: addSensor(String _sensorName,String sensorType)
activate D1
D1->F: createSensor(_sensorName, _sensorType)
activate F
F-->S1**: create (_sensorName, _sensorType)
F-->D1: _sensor
deactivate F
D1->SL: add(_sensor)
activate SL
deactivate SL
D1-->C7: _sensor
deactivate D1
C7->M1: mapSensorToSensorDTO(_sensor)
activate M1
M1-->S2**: create(_sensor)
M1-->C7: _sensorDTO
deactivate M1
[o<--C7: _sensorDTO


@enduml