@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant "_getRoomList:GetRoomListController" as C1
participant "_getDeviceList:GetDeviceListFromSpecificRoomController" as C2
participant "_deactivateDevice:DeactivateDeviceController" as C3
participant "_house:House" as H
participant "_room:Room" as R
participant "_device:Device" as D
participant "_mapperToDeviceDTO:MapperToDeviceDTO" as M1
participant "_deviceDTO:DeviceDTO" as D2

[o->C1: getRoomList()
activate C1
activate C2
ref over C1,C2 : (UseCase06.puml for more details)
[o<--C1: _deviceListDTO
deactivate C2
deactivate C1

[o->C3: deactivateDevice(DeviceDTO _devicedto)
activate C3
C3->H: getRoomByName(String _roomName)
H-->C3: _room
deactivate H
C3->R: getDeviceByName(String _deviceName)
activate R
R-->C3: _device
deactivate R
C3->D: deactivate()
activate D
deactivate D
C3->M1: mapToDeviceDTO(Device _device)
activate M1
M1-->D2**: create(_device)
M1-->C3: _deviceDTO
deactivate M1
[o<--C3: _deviceDTO
deactivate C3

@enduml