@startuml
'https://plantuml.com/sequence-diagram

autonumber

title US003

/'
As an Administrator, I want to have a list of existing rooms, so that I can choose one to edit it.
'/

participant "_getRoomListController:GetRoomListController" as C
participant "_house:House" as H
participant "RoomMapper:RoomMapper" as M

[o-> C: getRooms()
activate C
C -> H: getRooms()
activate H
H-->C: rooms
deactivate H
C -> M: roomToDTO(rooms)
activate M

M-->C: roomsDTO
deactivate M
[o<--C: roomsDTO


@enduml