@startuml

autonumber

title US005

/'
As a Power User [or Administrator], I want to add a new device to a room, in order to configure it.
'/

participant "getRoomListController:GetRoomListController" as G
participant "addDeviceController:AddDeviceToRoomController" as A
participant "house:House" as H
participant "room:Room" as R
participant "deviceFactory:DeviceFactory" as F
participant "device:Device" as D
participant "deviceMapper:DeviceMapper" as M
participant "deviceDTO:DeviceDTO" as DTO

[o->G : getRoomList()
activate G
ref over G : (UseCase003.puml for more details)
[o<--G : roomsDTO
deactivate G
[o->A : addDeviceToRoom(deviceDTO)
activate A
A->H : getRoomByName(roomName)
activate H
H-->A : room
deactivate H
A->R : addNewDevice(name, deviceType)
activate R
R->F : createDevice(name, deviceType)
activate F
F-->D** : create(name, deviceType,sensorFactory,actuatorFactory)
F-->R : device
deactivate F
R-->A : device
deactivate R
A->M : deviceToDTO(device, roomName)
activate M
M-->DTO** : create(device)
M-->A : deviceDTO
deactivate M
[o<--A : deviceDTO
deactivate A



@enduml