@startuml
'https://plantuml.com/sequence-diagram

autonumber

title US03

/'
As an Administrator, I want to have a list of existing rooms, so that I can choose one to edit it.
'/

participant "_getRoomListController:GetRoomListController" as C
participant "_house:House" as H
participant "_mapperToRoomDTO:MapperToRoomDTO" as M
participant "_listRoomDTO:List<RoomDTO>" as LRDTO

[o-> C: getRoomList()
activate C
C -> H: getRooms()
activate H
H-->C: _roomListCopy
deactivate H
C -> M: getRoomList(_roomList)
activate M
M-->LRDTO**:create(_roomList)
M-->C: _roomsDTO
deactivate M
[o<--C: _roomsDTO


@enduml