@startuml
'https://plantuml.com/sequence-diagram

title US009
autonumber

/'As a Power User [or Administrator], I want to get a list of all devices in a house,
grouped by device functionality types. It must include device location.'/

participant "_getDevices:GetListOfDevicesByFunctionalityController" as C
participant ":House" as H
participant "devicesByRoom:Map<String, List<Device>>" as DBR
participant "SensorType" as ST
participant ":Room" as R
participant "mapper:MapperToGroupDeviceDTO" as M
participant "devicesPerFunctionality:Hashmap" as HM


[o-> C : getDeviceByFunctionality()
activate C
C -> H : getDevicesGroupedByRoom()
activate H
H-->DBR** : create()
H --> C : devicesByRoom
deactivate H
C->ST : values()
activate ST
ST --> C : sensorTypes
deactivate ST
C -> M : groupDevicesByFunctionality(devicesByRoom, sensorTypes)
activate M
M-->HM** : create(functionalities, devicesByRoom)
M --> C : devicesPerFunctionality
deactivate M
[o<-- C : devicesPerFunctionality
deactivate C


note left #LightBlue
Assuming success
end note

@enduml

@enduml