@startuml

autonumber

title US001

/'
As an Administrator, I want to configure the location of the house.
'/

[o-> ": DefineHouseLocationController" : defineHouseLocation(LocationDTO)
activate ": DefineHouseLocationController"
": DefineHouseLocationController" -> ": House": defineLocation(address, zipCode, latitude, longitude)
activate ": House"
": House" -> ": LocationFactoryImp": createLocation(address, zipCode, latitude, longitude)
activate ": LocationFactoryImp"
": LocationFactoryImp" -->"_location : Location"** : createLocation(address, zipCode, latitude, longitude)
activate "_location : Location"
"_location : Location" ->": GPSFactoryImp" : createGPS(latitude, longitude)
activate ": GPSFactoryImp"
": GPSFactoryImp" -->"_gps : GPSLocation"** : createGPS(latitude, longitude)
": GPSFactoryImp" -->"_location : Location" : _gps
deactivate ": GPSFactoryImp"
"_location : Location" -->": LocationFactoryImp" : _location
deactivate "_location : Location"
": LocationFactoryImp" -->": House" : _location
deactivate ": LocationFactoryImp"

": House" -->": DefineHouseLocationController" : _location
deactivate ": House"
": DefineHouseLocationController" ->": LocationMapper" : locationToDTO(_location)
activate ": LocationMapper"
": LocationMapper" -->"_locationDTO : LocationDTO"** : createLocationDTO(address, zipCode, latitude, longitude)
": LocationMapper" -->": DefineHouseLocationController" : _locationDTO
deactivate ": LocationMapper"
[o<--": DefineHouseLocationController" : _locationDTO
deactivate ": DefineHouseLocationController"

@enduml