@startuml
'https://plantuml.com/sequence-diagram

title US009
autonumber

/'As a Power User [or Administrator], I want to get a list of all devices in a house,
grouped by device functionality types. It must include device location.'/

participant "_getDevices:GetListOfDevicesByFunctionalityController" as C
participant ":House" as H
participant "_devicesByRoom:Map<String, List<Device>>" as DBR
participant "SensorType" as ST
participant ":Room" as R
participant "_mapper:MapperToGroupDeviceDTO" as M
participant "_myMap:Hashmap" as HM


[o-> C : getDeviceByFunctionality()
activate C
C -> H : getDevicesGroupedByRoom()
activate H
H-->DBR** : create()
H --> C : _devicesByRoom
deactivate H
C->ST : values()
activate ST
ST --> C : _sensorTypes
deactivate ST
C -> M : groupDevicesByFunctionality(devicesByRoom, _availableFunctionalities)
activate M
M-->HM** : create(_availableFunctionalities, _devicesByRoom)
M --> C : _myMap
deactivate M
[o<-- C : _myMap
deactivate C


note left #LightBlue
Assuming success
end note

@enduml

@enduml