@startuml
'https://plantuml.com/sequence-diagram

autonumber

title US008

autonumber

/'
As a Power User [or Administrator], I want to deactivate a device, so that it is no
longer used. Nevertheless, it should be possible to access its configuration and
activity log.
'/

participant "_getRoomList:GetRoomListController" as C1
participant "_getDeviceList:GetDeviceListFromSpecificRoomController" as C2
participant "_deactivateDevice:DeactivateDeviceController" as C3
participant "_house:House" as H
participant "_room:Room" as R
participant "_device:Device" as D
participant "_mapperToDeviceDTO:MapperToDeviceDTO" as M1
participant "_deviceDTO:DeviceDTO" as D2


[o->C1 : getRoomList()
activate C1
ref over C1 : (UserStory3.puml for more details)
[o<--C1 : _roomListDTO
deactivate C1
[o->C2 : getDeviceList()
activate C2
ref over C2 : (UserStory6.puml for more details)
[o<--C2 : _deviceListDTO
deactivate C2

[o->C3: deactivateDevice(String _deviceName)
activate C3
C3->R: getDeviceByName(_deviceName)
activate R
R-->C3: _device
deactivate R
C3->D: deactivate()
activate D
deactivate D
C3->M1: mapToDeviceDTO(_device)
activate M1
M1-->D2**: create(_device)
M1-->C3: _deviceDTO
deactivate M1
[o<--C3: _deviceDTO
deactivate C3

@enduml
@enduml