@startuml

title DOMAIN MODEL (G6)

package "House Ag." {
entity House {
- houseName : HouseName
}
Object Location {
}
Object GPS {
- latitude : Latitude
- longitude : Longitude
}
object Address {
- street : Street
- number : Number
- city : City
- zipCode: ZipCode
}

}


package "Room Ag" {
entity Room {
- name : RoomName
- floor : Floor
- houseName : HouseName
}
object Dimensions {
- width : Width
- length : Length
- height : Height
}
}


package "Device Ag" {
entity Device {
- deviceId: DeviceId
- name : DeviceName
- type : DeviceType
- active : Active
- roomName : RoomName
}
}


package "Sensor Ag" {
entity Sensor {
- id : SensorId
- deviceId : DeviceId
- value : Value
}
Object SensorType {
- name : String
- measuringUnit : String
}

}

package "Actuator Ag" {
entity Actuator {
- id : ActuatorId
- deviceId : DeviceId
- state : State
}

Object ActuatorType {
- name: String
}

}

House "1" <-- "1"  Room
Room "1" <-- "1" Device
Device "1" <-- "1" Sensor
Device "1" <-- "1" Actuator

House "1" <--"1" Location
Location "1"<--"1" Address
Location "1"<-- "1" GPS

Room "1"<--"1" Dimensions

Sensor"1" <-- "1"SensorType

Actuator "1" <-- "1" ActuatorType






@enduml