@startuml

title US024

/'
As Product Owner, I want the system to have a type of sensor that gives the
power consumption in a given instant (W).
'/

interface Sensor {
    + getId() : int
    + generateId() : int
    + getType() : SensorType
    + getValue() : Value
}

class SensorOfPowerConsumption {
    - id : int
    - type : SensorType
    - value : Value
    + SensorOfPowerConsumption()
    + getId() : int
    + generateId() : int
    + getType() : SensorType
    + getValue() : Value
}

interface Value {
    + valueToString() : String
}

class PowerConsumptionValue {
    - powerConsumptionValue : double
    + PowerConsumptionValue(double)
    + valueToString() : String
}

enum SensorType {
    - type : SensorType
    + SensorType(...)
    + getSensorType() : String
}

SensorOfPowerConsumption ..|> Sensor : " implements       "
PowerConsumptionValue ..|> Value : " implements"
SensorOfPowerConsumption "1  " *-- "1    " PowerConsumptionValue :  "  has"
SensorOfPowerConsumption "1  " o-- "1  " SensorType :  "  has"


@enduml