@startuml
'https://plantuml.com/sequence-diagram

title US007

autonumber

/'
As a Power User [or Administrator], I want to add a sensor to an existing device in
a room. The sensor must be of a model of an existing type of sensor.
'/

participant "addSensorToDeviceController:AddSensorToDeviceController" as C7
participant "getRoomList:GetRoomListController" as C
participant "getDeviceList:GetDeviceListController" as D
participant "sensorType:SensorType" as ST
participant "catalogue:Catalogue" as CAT
participant "sensorFactory:SensorFactory" as F
participant "sensor:Sensor" as S1
participant "sensorRepository:SensorRepository" as SR
participant "sensorMapper:SensorMapper" as S3
participant "sensorDTO:SensorDTO" as S2


participant "sensorIdMapper:SensorIdMapper" as S4
participant "sensorId:SensorId" as SID
participant "sensorIdDTO:SensorIdDTO" as id
participant "sensorTypesMapper:SensorTypesMapper" as S6
participant "sensorTypeDTO:SensorTypeDTO" as S5
participant "deviceNameMapper:DeviceNameMapper" as DN1
participant "deviceName:DeviceName" as D7
participant "deviceNameDTO:DeviceNameDTO" as DN


[o->C7 : getRooms()
activate C7
C7->C : getRooms()
activate C
ref over C : (UserStory3.puml for more details)
C-->C7 : _roomsDTO
deactivate C
[o<--C7 : _roomsDTO
deactivate C7

[o->C7 : getDevices()
activate C7
C7->D : getDevices()
activate D
ref over D : (UserStory6.puml for more details)
D-->C7 : _devicesDTO
deactivate D
[o<--C7 : _devicesDTO
deactivate C7

[o->C7 : getSensorTypes()
activate C7
C7 -> ST : values()
activate ST
ST --> C7 : sensorTypes
deactivate ST
[o<--C7 : sensorTypes
deactivate C7



[o->C7: getSensorModelByType(type)
activate C7
C7->CAT : getSensorModelByType(type)
activate CAT
CAT-->C7 : sensorModels
deactivate CAT
[o<--C7 : sensorModels
deactivate C7

[o->C7: addSensorToDevice(sensorDTO, sensorModel)
activate C7
C7 -> S4 : toSensorId(sensorDTO)
activate S4
S4 --> SID** : <create>(sensorId)

S4 --> C7 : sensorId
deactivate S4
C7 -> DN1 : toDeviceName(sensorDTO)
activate DN1
DN1 --> D7** : <create>(deviceName)
DN1 --> C7 : deviceName
deactivate DN1


C7 -> F : createSensor(sensorModel, sensorId, deviceName)
activate F
F --> S1** : createSensor(sensorModel, sensorId, deviceName, value)
F --> C7 : sensor
deactivate F
C7 -> SR : save(sensor)
activate SR
SR --> C7 : sensor
deactivate SR

C7 -> S3 : sensorToDTO(sensor)
activate S3
S3 -> S4 : sensorIdToDTO(sensorId)
activate S4
S4 --> id** : <create>(sensorId)
S4 --> S3 : sensorIdDTO
deactivate S4
S3 -> S6 : sensorTypeToDTO(sensorType)
activate S6
S6 --> S5** : <create>(sensorType)
S6 --> S3 : sensorTypeDTO
deactivate S6
S3 -> DN1 : deviceNameToDTO(deviceName)
activate DN1
DN1 --> DN** : <create>(deviceName)
DN1 --> S3 : deviceNameDTO
deactivate DN1
S3 --> S2** : <create>(sensorIdDTO, sensorTypeDTO, deviceNameDTO)
S3 --> C7 : sensorDTO
deactivate S3
[o<-- C7 : sensorDTO




deactivate C7
@enduml