@startuml
'https://plantuml.com/sequence-diagram

autonumber

title US002

/'As an Administrator, I want to add a new room to the house, in order to
  configure it (name, house floor and dimensions).'/
/'
As an Administrator, I want to add a new room to the house, in order to
configure it (name, house floor and dimensions).
'/

participant "addRoomController:AddRoomController" as ARC
participant "roomMapper:RoomMapper" as RM
participant "houseNameMapper:HouseNameMapper" as HNM
participant "roomNameMapper:RoomNameMapper" as RNM
participant "houseName:HouseName" as HN
participant "roomName:RoomName" as RN
participant "floorMapper:FloorMapper" as FM
participant "floor:Floor" as F
participant "dimensionMapper:DimensionMapper" as DM
participant "dimension:Dimension" as D
participant "roomFactory:RoomFactory" as RF
participant "room:Room" as R
participant "roomRepo:RoomRepository" as RR
participant "houseNameDTO:HouseNameDTO" as HND
participant "roomName:RoomNameDTO" as RDT
participant "floorDTO:FloorDTO" as FD
participant "dimensionDTO:DimensionDTO" as DD
participant "roomDTO:RoomDTO" as RD

[o-> ARC : addRoom(roomDTO)
activate ARC
ARC -> HNM : toHouseName(roomDTO)
activate HNM
HNM --> HN** : <create>(houseName)
HNM --> ARC : houseName
deactivate HNM
ARC -> RNM : toRoomName(roomDTO)
activate RNM
RNM --> RN** : <create>(roomName)
RNM --> ARC : roomName
deactivate RNM
ARC -> FM : toFloor(roomDTO)
activate FM
FM --> F** : <create>(floor)
FM --> ARC : floor
deactivate FM
ARC -> DM : toDimension(roomDTO)
activate DM
DM --> D** : <create>(width, height, length)
DM --> ARC : dimension
deactivate DM
ARC -> RF : createRoom(houseName, roomName, floor, dimension)
activate RF
RF --> R** : <create>(houseName, roomName, floor, dimension)
RF --> ARC : room
deactivate RF
ARC -> RR : save(room)
activate RR
RR --> ARC : room
deactivate RR
ARC -> RM : toRoomDTO(room)
activate RM
RM -> HNM : toHouseNameDTO(houseName)
activate HNM
HNM --> HND** : <create>(houseName)
HNM --> RM : houseNameDTO
deactivate HNM
RM -> RNM : toRoomNameDTO(roomName)
activate RNM
RNM --> RDT** : <create>(roomName)
RNM --> RM : roomNameDTO
deactivate RNM
RM -> FM : toFloorDTO(floor)
activate FM
FM --> FD** : <create>(floor)
FM --> RM : floorDTO
deactivate FM
RM -> DM : toDimensionDTO(dimension)
activate DM
DM --> DD** : <create>(width, height, length)
DM --> RM : dimensionDTO
deactivate DM
RM --> RD** : <create>(houseNameDTO, roomNameDTO, floorDTO, dimensionDTO)
RM --> ARC : roomDTO
deactivate RM
[o<-- ARC : roomDTO
deactivate ARC

@enduml
