@startuml
'https://plantuml.com/sequence-diagram

autonumber

title US008

/'
As a Power User [or Administrator], I want to deactivate a device, so that it is no
longer used. Nevertheless, it should be possible to access its configuration and
activity log.
'/


participant "deactivateDevice:DeactivateDeviceController" as C1
participant "getRoomList:GetRoomListController" as C2
participant "getDeviceList:GetDeviceListController" as C3
participant "house:House" as H
participant "room:Room" as R
participant "mapperToDeviceDTO:MapperToDeviceDTO" as M1
participant "deviceIdMapper:DeviceIdMapper" as M2
participant "deviceNameMapper:DeviceNameMapper" as M3
participant "deviceDTO:DeviceDTO" as D2
participant "deviceRepository:DeviceRepository" as DR
participant "device:Device" as D
participant "deviceId:DeviceId" as DN

participant "deviceIdDTO:DeviceIdDTO" as DNDTO
participant "deviceNameDTO:DeviceNameDTO" as DNDTO1
participant "deviceTypeMapper:DeviceTypeMapper" as DTM
participant "typeDTO:TypeDTO" as TDTO
participant "statusMapper:StatusMapper" as SM
participant "statusDTO:StatusDTO" as SDTO
participant "roomNameMapper:RoomNameMapper" as RNM
participant "roomNameDTO:RoomNameDTO" as RNDTO

[o->C1 : getRooms()
activate C1
C1->C2 : getRooms()
activate C2
ref over C2 : (UserStory3.puml for more details)
C2-->C1 : roomsDTO
deactivate C2
[o<--C1 : roomsDTO
deactivate C1
[o->C1 : getDevices()
activate C1
C1->C3 : getDevices()
activate C3
ref over C3 : (UserStory6.puml for more details)
C3-->C1 : devicesDTO
deactivate C3
[o<--C1 : devicesDTO
deactivate C1


[o->C1 : deactivateDevice(deviceIdDTO)
activate C1
C1 -> M2 : toDeviceId(deviceIdDTO)
activate M2
M2 --> DN** : <create> (deviceId)
M2 --> C1 : deviceId
deactivate M2
C1 -> DR : getDeviceById(deviceId)
activate DR
DR --> C1 : device
deactivate DR
C1 -> D : deactivate()
activate D
D --> C1 : device
deactivate D

C1 -> M1 : toDeviceDTO(device)
activate M1
M1 -> M2 : toDeviceIdDTO(deviceId)
activate M2
M2 --> DNDTO** : <create> (deviceId)
M2 --> M1 : deviceIdDTO
deactivate M2
M1-> M3 : toDeviceNameDTO(deviceName)
activate M3
M3 --> DNDTO1** : <create> (deviceName)
M3 --> M1 : deviceNameDTO
deactivate M3
M1 -> DTM : toTypeDTO(type)
activate DTM
DTM --> TDTO** : <create> (type)
DTM --> M1 : typeDTO
deactivate DTM
M1 -> SM : toStatusDTO(status)
activate SM
SM --> SDTO** : <create> (status)
SM --> M1 : statusDTO
deactivate SM
M1 -> RNM : toRoomNameDTO(roomName)
activate RNM
RNM --> RNDTO** : <create> (roomName)
RNM --> M1 : roomNameDTO
deactivate RNM
M1 --> D2** : <create> (deviceIdDTO, typeDTO, statusDTO, roomNameDTO)
M1 --> C1 : deviceDTO
deactivate M1
[o<--C1 : deviceDTO


deactivate C1

@enduml