@startuml
'https://plantuml.com/sequence-diagram

autonumber

title US001

/'
As an Administrator, I want to configure the location of the house.
'/
/'
As an Administrator, I want to configure the location of the house.
'/

participant "locationController:DefineHouseLocationController" as LC
participant "mapper:LocationMapper" as M
participant "gpsMapper:GpsMapper" as G
participant "gps:Gps" as GPS
participant "addressMapper:AddressMapper" as A
participant "address:Address" as AD
participant "location:Location" as L
participant "houseRepo:HouseRepo" as HF
participant "house:House" as H
participant "gpsDTO:GpsDTO" as GPSDTO
participant "addressDTO:AddressDTO" as ADTO
participant "locationDTO:LocationDTO" as DTO

[o-> LC : defineHouseLocation(locationDTO)
activate LC
LC->M : toLocation(locationDTO)
activate M
M->G : toGPS(gpsDTO)
activate G
G-->GPS** : <create>(latitude,longitude)
G-->M : gps
deactivate G
M->A : toAddress(addressDTO)
activate A
A-->AD** : <create>(street,number,city,zipcode)
A-->M : address
deactivate A
M-->L** : <create>(address,gps)
M-->LC : location
deactivate M
LC->HF : getHouse()
activate HF
HF-->LC : house
deactivate HF
LC->H : defineLocation(location)
activate H
H-->LC : location
deactivate H
LC -> M : toLocationDTO(location)
activate M
M->G : toGpsDTO(gps)
activate G
G-->GPSDTO** : <create>(latitude,longitude)
G-->M : gpsDTO
deactivate G
M->A : toAddressDTO(address)
activate A
A-->ADTO** : <create>(street,number,city,zipcode)
A-->M : addressDTO
deactivate A
M-->DTO** : <create>(addressDTO,gpsDTO)
M-->LC : locationDTO
deactivate M
[o<-- LC : locationDTO
deactivate LC

@enduml
