@startuml
'https://plantuml.com/sequence-diagram

autonumber

title US003

/'
As an Administrator, I want to have a list of existing rooms, so that I can choose one to edit it.
'/

participant "getRoomsController:GetRoomsController" as GRC
participant "roomRepository:RoomRepository" as RR
participant "roomMapper:RoomMapper" as RM
participant "houseNameMapper:HouseNameMapper" as HNM
participant "roomNameMapper:RoomNameMapper" as RNM
participant "floorMapper:FloorMapper" as FM
participant "dimensionMapper:DimensionMapper" as DM
participant "houseNameDTO:HouseNameDTO" as HND
participant "roomName:RoomNameDTO" as RDT
participant "floorDTO:FloorDTO" as FD
participant "dimensionDTO:DimensionDTO" as DD
participant "roomDTO:RoomDTO" as RD

[o-> GRC: getRooms()
activate GRC
GRC -> RR: getRooms()
activate RR
RR --> GRC: rooms
deactivate RR
GRC -> RM : toRoomsDTO(rooms)
activate RM
loop FOR EACH ROOM
RM -> HNM : toHouseNameDTO(houseName)
activate HNM
HNM --> HND** : <create>(houseName)
HNM --> RM : houseNameDTO
deactivate HNM
RM -> RNM : toRoomNameDTO(roomName)
activate RNM
RNM --> RDT** : <create>(roomName)
RNM --> RM : roomNameDTO
deactivate RNM
RM -> FM : toFloorDTO(floor)
activate FM
FM --> FD** : <create>(floor)
FM --> RM : floorDTO
deactivate FM
RM -> DM : toDimensionDTO(dimension)
activate DM
DM --> DD** : <create>(width, height, length)
DM --> RM : dimensionDTO
deactivate DM
RM --> RD** : <create>(houseNameDTO, roomNameDTO, floorDTO, dimensionDTO)
end
RM --> GRC : roomsDTO
deactivate RM
[o<-- GRC : roomsDTO
deactivate GRC

@enduml
