@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant "getRoomsController:GetRoomsController"
participant "roomRepo:RoomRepo"
participant "roomMapper:RoomMapper"

[o-> "getRoomsController:GetRoomsController": getRooms(houseID)
activate "getRoomsController:GetRoomsController"
"getRoomsController:GetRoomsController" -> "roomRepo:RoomRepo": getRoomsByHouseID(houseID)
activate "roomRepo:RoomRepo"
"roomRepo:RoomRepo" --> "getRoomsController:GetRoomsController": rooms
deactivate "roomRepo:RoomRepo"
"getRoomsController:GetRoomsController" -> "roomMapper:RoomMapper": roomsToDTO(rooms)
activate "roomMapper:RoomMapper"
"roomMapper:RoomMapper" --> "getRoomsController:GetRoomsController": roomsDTO
deactivate "roomMapper:RoomMapper"
[o<-- "getRoomsController:GetRoomsController": roomsDTO
deactivate "getRoomsController:GetRoomsController"

@enduml