@startuml
'https://plantuml.com/sequence-diagram

title US009
autonumber

/'
As a Power User [or Administrator], I want to get a list of all devices in a house,
grouped by device functionality types. It must include device location.
'/

participant "_getDevices:GetListOfDevicesByFunctionalityController" as C
participant "SensorType" as ST
participant "mapFunctionalities:HashMap<Functionality, List<Device>>" as M
participant "deviceRepository:DeviceRepository" as DR
participant "mapperDevice:MapperDevice" as MD
participant "mapFunctionalitiesDTO:HashMap<Functionality, List<DeviceDTO>>" as MDTO

[o-> C : getDevicesByFunctionality()
activate C
C-> ST : values()
activate ST
ST --> C : sensorTypes
deactivate ST
C --> M** : <create>(sensorTypes)
C-> DR : getDevicesByFunctionality(mapFunctionalities)
activate DR

loop [for device in deviceRepository]
    loop [for functionality in device.getFunctionalities()]
        DR -> M : get(functionality).add(device)
        activate M
    end loop
    deactivate M
end loop
deactivate M
DR --> C : mapFunctionalities
deactivate DR
C -> MD : deviceToDTO(mapFunctionalities)
activate MD
MD --> MDTO** : <create>(mapFunctionalities)
MD--> C : mapFunctionalitiesDTO
deactivate MD
[o<--C : mapFunctionalitiesDTO
deactivate C

@enduml

@enduml