@startuml

class House {
    + getCatalogue() : Catalogue
    + getRoomList() : List<Room>
    + getRoomByName(...) : Room

}

class Catalogue {
  - sensorList : List<String>

  + addSensorType(...) : boolean
  + getCatalogue() : List<String>
}

class AddSensorToDeviceController {
    - house : House

    + AddSensorToDeviceController()
    + getRoomList() : List<RoomDTO>
    + getDeviceList() : List<DeviceDTO>
    + getSensorTypeDTO(...) : SensorTypeDTO
    + addSensorToExistingDevice(...) : boolean
}

class Device {
    - name : String
    - type : String
    - sensorList : List<Sensor>
    - actuatorList : List<Actuator>

    + Device(...)
    + getName() : String
    + getType() : String
    + addSensor(...) : boolean
}

interface Sensor {

    + getType() : String
    + getName() : String
}

class SensorOfTemperature {
    - name : String
    - type : String

    + SensorOfTemperature(...)
}

class SensorOfHumidity {
    - name : String
    - type : String

    + SensorOfHumidity(...)
}

class Room {
    - name : String
    - floor : int

    + Room(...)
    + getName() : String
    + getFloor() : int
    + getWidth() : double
    + getLength() : double
    + getHeight() : double
    + getDeviceList() : List<Device>
    + getDeviceByName(...) : Device
}

class MapperSensorTypeDTO {

    + MapperSensorTypeDTO()
    + getSensorTypes(...) : SensorTypeDTO
}

class MapperToRoomDTO {

    + MapperToRoomDTO()
    + getRoomList(...) : List<RoomDTO>
    - toRoomDTO(...) : RoomDTO
}

class MapperToDeviceDTO {

    + MapperToDeviceDTO()
    + getDeviceList(...) : List<DeviceDTO>
    - toDeviceDTO(...) : DeviceDTO
}

class GetRoomListController {
    - house : House

    + GetRoomListController()
    + getRoomList(...) : List<RoomDTO>
}

class GetDeviceListController {
    - house : House

    + GetDeviceListController()
    + getDeviceList(...) : List<DeviceDTO>
}

class SensorTypeDTO {
    - sensorTypes : List<String>

    + SensorTypeDTO(...)
    + getSensorTypes() : List<String>
}

class RoomDTO {
    - name : String
    - floor : int
    - width : double
    - length : double
    - height : double

    + RoomDTO(...)
    + getName() : String
    + getFloor() : int
    + getWidth() : double
    + getLength() : double
    + getHeight() : double
}

class DeviceDTO {
    - name : String
    - type : String
    - location : String

    + DeviceDTO(...)
    + getName() : String
    + getType() : String
    + getLocation() : String
}

class SensorDTO {
    - sensorName : String
    - typeOfSensor : String

    + SensorDTO(...)
    + getSensorName() : String
    + getTypeOfSensor() : String
}

class Dimensions {
    - width : double
    - length : double
    - height : double

    + Dimensions(...)
    + getWidth() : double
    + getLength() : double
    + getHeight() : double
}

House "1" *--> "1" Catalogue: has
AddSensorToDeviceController "1" --> "1" House: uses
AddSensorToDeviceController "1" --> "1" GetRoomListController: uses
GetRoomListController "1" --> "1" MapperToRoomDTO: uses
GetRoomListController "1" --> "1" House: uses
House "1" *--> "List<Room>" Room: contains
MapperToRoomDTO "1" --> "List<RoomDTO>" RoomDTO: uses
AddSensorToDeviceController "1" --> "1" GetDeviceListController: uses
GetDeviceListController "1" --> "1" MapperToDeviceDTO: uses
MapperToDeviceDTO "1" --> "List<DeviceDTO>" DeviceDTO: uses
AddSensorToDeviceController "1" --> "1" MapperSensorTypeDTO: uses
MapperSensorTypeDTO "1" --> "1" SensorTypeDTO: creates
Room "1" *--> "List<Device>" Device: contains
SensorOfTemperature "*" --> "1" Sensor: implements
SensorOfHumidity "*" --> "1" Sensor: implements
Device "1" *--> "1" SensorOfTemperature: creates
Device "1" *--> "1" SensorOfHumidity: creates
AddSensorToDeviceController "1" --> "1" DeviceDTO: uses
AddSensorToDeviceController "1" --> "1" SensorDTO: uses
Room "1" --> "1" Dimensions: has

@enduml