@startuml

class House {
  + getDevicesGroupedByRoom() : Map<...>
}

class Room {
  - deviceList : List<Device>
  + getRoomName() : String
  + getDeviceList() : List<Device>
}

class Device {
  - functionalityList : HashSet<String>
  + getFunctionalities() : HashSet<String>
}

class GetListOfDevicesByFunctionalityController {
  - house : House
  + GetListOfDevicesByFunctionalityController(...)
  + getDeviceByFunctionality() : Map<String,List<DeviceDTO>
}

class MapperToGroupDeviceDTO {
    + MapperToGroupDeviceDTO()
    + groupDevicesByFunctionality(...) : Map<String,List<DeviceDTO>>
}

class DeviceDTO {
    - name : String
    - type : String
    - roomName : String
    + getName() : String
    + getType() : String
    + getRoomName() : String
}

enum SensorType {
- String sensorType
- String measuringUnit
+ SensorType(...)
+values() : SensorType[]
}

House "1" <.. "1" GetListOfDevicesByFunctionalityController : uses
House "1" *-- "*" Room : contains
Room "1" *-- "*" Device : contains

GetListOfDevicesByFunctionalityController "1" ..> "1" MapperToGroupDeviceDTO : creates
GetListOfDevicesByFunctionalityController "1" ..> "1..*" SensorType : uses"
MapperToGroupDeviceDTO "1" ..> "List<DeviceDTO>" DeviceDTO : creates

@enduml