@startuml
'https://plantuml.com/sequence-diagram

autonumber

title US002

/'
As an Administrator, I want to add a new room to the house, in order to
configure it.
'/

participant "addRoomController:AddRoomController" as ARC
participant "roomMapper:RoomMapper" as RM
participant "houseNameMapper:HouseNameMapper" as HNM
participant "houseName:HouseName" as HN
participant "roomNameMapper:RoomNameMapper" as RNM
participant "roomName:RoomName" as RN
participant "floorMapper:FloorMapper" as FM
participant "floor:Floor" as F
participant "dimensionsMapper:DimensionsMapper" as DM
participant "dimensions:Dimensions" as D
participant "roomFactory:RoomFactory" as RF
participant "room:Room" as R
participant "roomRepo:RoomRepository" as RR
participant "houseNameDTO:HouseNameDTO" as HND
participant "roomName:RoomNameDTO" as RDT
participant "floorDTO:FloorDTO" as FD
participant "dimensionsDTO:DimensionsDTO" as DD
participant "roomDTO:RoomDTO" as RD

[o-> ARC : addRoom(roomDTO)
activate ARC
ARC -> RM : toHouseName(roomDTO)
activate RM
RM -> HNM : toHouseName(roomDTO)
activate HNM
HNM --> HN** : <create>(houseName)
HNM --> RM : houseName
deactivate HNM
RM --> ARC : houseName
deactivate RM
ARC -> RM : toRoomName(roomDTO)
activate RM
RM -> RNM : toRoomName(roomDTO)
activate RNM
RNM --> RN** : <create>(roomName)
RNM --> RM : roomName
deactivate RNM
RM --> ARC : roomName
deactivate RM
ARC ->  RM : toFloor(roomDTO)
activate RM
RM -> FM : toFloor(roomDTO)
activate FM
FM --> F** : <create>(floor)
FM --> RM : floor
deactivate FM
RM --> ARC : floor
deactivate RM
ARC -> RM : toDimensions(roomDTO)
activate RM
RM -> DM : toDimensions(roomDTO)
activate DM
DM --> D** : <create>(width, height, length)
DM --> RM : dimensions
deactivate DM
RM --> ARC : dimensions
deactivate RM
ARC -> RF : createRoom(houseName, roomName, floor, dimensions)
activate RF
RF --> R** : <create>(houseName, roomName, floor, dimensions)
RF --> ARC : room
deactivate RF
ARC -> RR : save(room)
activate RR
RR --> ARC : room
deactivate RR
ARC -> RM : toRoomDTO(room)
activate RM
RM -> HNM : toHouseNameDTO(houseName)
activate HNM
HNM --> HND** : <create>(houseName)
HNM --> RM : houseNameDTO
deactivate HNM
RM -> RNM : toRoomNameDTO(roomName)
activate RNM
RNM --> RDT** : <create>(roomName)
RNM --> RM : roomNameDTO
deactivate RNM
RM -> FM : toFloorDTO(floor)
activate FM
FM --> FD** : <create>(floor)
FM --> RM : floorDTO
deactivate FM
RM -> DM : toDimensionsDTO(dimension)
activate DM
DM --> DD** : <create>(width, height, length)
DM --> RM : dimensionsDTO
deactivate DM
RM --> RD** : <create>(houseNameDTO, roomNameDTO, floorDTO, dimensionsDTO)
RM --> ARC : roomDTO
deactivate RM
[o<-- ARC : roomDTO
deactivate ARC

@enduml
