@startuml
'https://plantuml.com/sequence-diagram

autonumber

title US002

/'
As an Administrator, I want to add a new room to the house, in order to
configure it.
'/

participant "addRoomController:AddRoomController" as ARC
participant "roomMapper:RoomMapper" as RM
participant "houseName:HouseName" as HN
participant "roomName:RoomName" as RN
participant "floor:Floor" as F
participant "dimensions:Dimensions" as D
participant "roomFactory:RoomFactory" as RF
participant "room:Room" as R
participant "roomRepo:RoomRepository" as RR
participant "roomDTO:RoomDTO" as RD

[o-> ARC : addRoom(roomDTO)
activate ARC
ARC -> RM : toHouseName(roomDTO)
activate RM
RM --> HN** : <create>(houseName)
RM --> ARC : houseName
deactivate RM
ARC -> RM : toRoomName(roomDTO)
activate RM
RM --> RN** : <create>(roomName)
RM --> ARC : roomName
deactivate RM
ARC ->  RM : toFloor(roomDTO)
activate RM
RM --> F** : <create>(floor)
RM --> ARC : floor
deactivate RM
ARC -> RM : toDimensions(roomDTO)
activate RM
RM --> D** : <create>(height, width, length)
RM --> ARC : dimensions
deactivate RM

ARC -> RF : createRoom(houseName, roomName, floor, dimensions)
activate RF
RF --> R** : <create>(houseName, roomName, floor, dimensions)
RF --> ARC : room
deactivate RF
ARC -> RR : save(room)
activate RR
RR --> ARC : room
deactivate RR

ARC -> RM : toRoomDTO(room)
activate RM

RM --> RD** : <create>(houseName, roomName, floor, height, width, length)
RM --> ARC : roomDTO
deactivate RM
[o<-- ARC : roomDTO
deactivate ARC

@enduml
