@startuml

title US013

/'As Product Owner, I want the system to have a type of actuator that switches a
  load ON/OFF.'/

interface Actuator {
    + getType() : ActuatorType
    + operate(Value) : Value
    + getId() : int
    + generateId() : int
}

class ActuatorOfOnOffSwitch {
    - id: int
    - type: ActuatorType
    - isLoadTurnedOn: boolean
    + ActuatorOfOnOffSwitch()
    + getType() : ActuatorType
    + operate(Value) : Value
    + getId() : int
    + generateId() : int
}


enum ActuatorType{
    - name : String
    + ActuatorType(...)
}

ActuatorOfOnOffSwitch"*" ..|>"1" Actuator : " implements"
ActuatorOfOnOffSwitch"1" o-- "1" ActuatorType : "contains"

@enduml