@startuml

title US015

/'
As a Product Owner, I want the system to have a type of actuator that sets an integer value in the range defined by [lower limit, upper limit].
'/

interface Actuator {
    + getId() : int
    + generateId(...) : int
    + getType() : ActuatorType
    + operate(...) : Value
}

class ActuatorOfLimiter {
    - id : int
    - lower : int
    - upper : int
    + ActuatorOfLimiter(...)
    + getId() : int
    + generateId(...) : int
    + getType() : ActuatorType
    + operate(...) : Value
}


enum ActuatorType{
    - name : String
    + ActuatorType(...)
}

ActuatorOfLimiter ..|> Actuator : " implements"
ActuatorOfLimiter"1" o-- "1" ActuatorType : "contains"

@enduml