@startuml

title US018

/'
As Product Owner, I want the system to have a type of sensor that gives the wind
speed (km/h) and direction (8 cardinal points).
'/

interface Sensor {
    + getId() : int
    + generateId(int) : int
    + getType() : SensorType
    + getValue() : Value
}

class SensorOfWind {
    - id : int
    + SensorOfWind()
    + getId() : int
    + generateId(int) : int
    + getType() : SensorType
    + getValue() : Value
}

interface Value {
    + valueToString() : String
}

class WindValue {
    - windDirection : double
    - windSpeed : double
    + WindValue(...)
    + valueToString() : String
}

enum SensorType {
    - sensorType : String
    - measureUnit : String
    + SensorType(...)
    + getSensorType() : String
}

Sensor <|.. SensorOfWind  : " implements       "
Value <|.. WindValue : " implements"
SensorOfWind  "1  " *-- "1    " WindValue :  "  has"
SensorOfWind  "1  " o-- "1  " SensorType :  "  has"

@enduml